import type { GlossaryContent } from "./types";

export const glossaryContent: GlossaryContent = {
  hero: {
    eyebrow: "Glossary",
    title: "Glossary",
    description:
      "A curated index of alternative investment terms so every team shares the same definitions and context.",
  },
  terms: [
    "2 and 20 Fee Structure",
    "144A Securities",
    "3/5/10 Rule",
    "Absolute Return",
    "Accredited Investor",
    "Activist Investing",
    "Add-On Acquisition",
    "Alpha Generation",
    "Angel Investor",
    "Arbitrage",
    "Asset Stripping",
    "Asset Under Management (AUM)",
    "Beta",
    "Bridging Loan",
    "Burn Rate",
    "Buyout",
    "Capital Call",
    "Capitalization Table (Cap Table)",
    "Carried Interest",
    "Club Deal",
    "Co-Investment",
    "Committed Capital",
    "Control Premium",
    "Convertible Arbitrage",
    "Convertible Note",
    "Deal Flow",
    "Disruptive Technology",
    "Distressed Investing",
    "Down Round",
    "Drag-Along Rights",
    "Drawdown",
    "Due Diligence",
    "Early-Stage Financing",
    "EBITDA",
    "Enterprise Value",
    "Event-Driven Strategy",
    "Exchange-Traded Fund (ETF)",
    "Exit Strategy",
    "Exit Valuation",
    "Follow-On Investment",
    "Fund of Hedge Funds",
    "Fundraising",
    "General Partner (GP)",
    "Global Macro Strategy",
    "Hedge Fund Manager",
    "Hedge Funds",
    "High-Water Mark",
    "Holding Period",
    "Hurdle Rate",
    "Incubator",
    "Initial Coin Offering (ICO)",
    "Initial Public Offering (IPO)",
    "Internal Rate of Return (IRR)",
    "J–Curve",
    "Key Person Provision",
    "KYC (Know Your Customer)",
    "Later-Stage Financing",
    "Leverage",
    "Leveraged Buyout (LBO)",
    "Limited Partner (LP)",
    "Limited Partnership Agreement (LPA)",
    "Liquidation Preference",
    "Lock-Up Period",
    "Long/Short Equity",
    "Managed Futures",
    "Management Buyout (MBO)",
    "Market Neutral",
    "Master-Feeder Structure",
    "Merger Arbitrage",
    "Mezzanine Financing",
    "Multiple on Invested Capital (MOIC)",
    "Multi-Strategy Hedge Fund",
    "Net Asset Value (NAV)",
    "Net Exposure",
    "Net Performance",
    "Nominee/(Bare) trust",
    "Notary",
    "Opportunistic Real Estate Strategy",
    "Option Pool",
    "Pair Trading",
    "Performance Fee",
    "Pivot",
    "Portfolio Company",
    "Post-Money Valuation",
    "Preferred Return",
    "Preferred Stock",
    "Pre-Money Valuation",
    "Prime Brokerage",
    "Private Equity",
    "Private Investment in Public Equity (PIPE)",
    "Pro Rata Rights",
    "Qualified Client",
    "Qualified Purchaser",
    "Quartile",
    "Recapitalization",
    "Redemption Notice Period",
    "Relative Value Strategy",
    "Runway",
    "SAFE (Simple Agreement for Future Equity)",
    "Secondary Buyout",
    "Seed Capital",
    "Seed Funding",
    "Series A, B, C Funding",
    "Sharpe Ratio",
    "Side Pocket",
    "Soft Lock-Up",
    "Startup",
    "Statistical Arbitrage",
    "Structured Credit",
    "Subscription Line of Credit",
    "Target Company",
    "Term Sheet",
    "Trade Sale",
    "Unicorn",
    "Venture Capital",
    "Venture Debt",
    "Vesting Schedule",
    "Volatility Arbitrage",
    "Waterfall Distribution",
    "Working Capital",
    "XIRR (Extended Internal Rate of Return)",
    "Yield",
    "Zero-Beta Portfolio",
    "Z-Score",
  ],
};
